In [1]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore", category=SyntaxWarning)

In [2]:
#@title 🔄 Colab & Local Jupyter Folder Switcher (click to expand)

# 🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# 🚨        Change only this 🚨
relative_path = "_datasets" #🚨 any relative path
# 🚨        Change only this 🚨
# 🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

import os

create_if_missing = True      # False = error if folder missing

def in_colab() -> bool:
    try:
        import google.colab  # noqa: F401
        return True
    except ImportError:
        return False

def paths_equal(a: str, b: str) -> bool:
    """Portable path equality (no os.path.samepath)."""
    return os.path.normcase(os.path.realpath(a)) == os.path.normcase(os.path.realpath(b))

def resolve_local_base(rel_path: str) -> str:
    pinned = os.getenv("NOTEBOOK_ROOT")
    if pinned:
        return pinned
    cwd = os.path.abspath(os.getcwd())
    rel_name = os.path.basename(os.path.normpath(rel_path))
    base = os.path.dirname(cwd) if rel_name and os.path.basename(cwd) == rel_name else cwd
    os.environ["NOTEBOOK_ROOT"] = base
    return base

def resolve_colab_base(rel_path: str) -> str:
    pinned = os.getenv("COLAB_ROOT")
    if pinned:
        return pinned
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)
    mydrive = "/content/drive/MyDrive"
    colab_nb = os.path.join(mydrive, "Colab Notebooks")
    base = colab_nb if os.path.isdir(colab_nb) else mydrive
    os.environ["COLAB_ROOT"] = base
    return base

# --- Pick base path ---
if in_colab():
    print("✅ Detected Google Colab")
    base_path = resolve_colab_base(relative_path)
else:
    print("✅ Detected Local Jupyter")
    base_path = resolve_local_base(relative_path)

# --- Build target path ---
if os.path.isabs(relative_path):
    target_path = os.path.abspath(relative_path)
else:
    target_path = os.path.abspath(os.path.join(base_path, relative_path))

current = os.path.abspath(os.getcwd())
rel_name = os.path.basename(os.path.normpath(relative_path))
if rel_name and os.path.basename(current) == rel_name:
    target_path = current

# --- Ensure exists ---
if not os.path.exists(target_path):
    if create_if_missing:
        os.makedirs(target_path, exist_ok=True)
        print(f"📁 Created folder: {target_path}")
    else:
        raise FileNotFoundError(f"❌ Path does not exist: {target_path}")

# --- Change only if needed ---
if paths_equal(current, target_path):
    print(f"📂 Already working in: {current}")
else:
    os.chdir(target_path)
    print(f"📂 Now working in: {os.path.abspath(os.getcwd())}")


✅ Detected Local Jupyter
📂 Now working in: /Users/jayklarin/Documents/__DI/Repositories/di_bootcamp/Colab-Swap/_datasets


In [3]:
df = pd.read_csv('Tweets.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   textID         27481 non-null  object
 1   text           27480 non-null  object
 2   selected_text  27480 non-null  object
 3   sentiment      27481 non-null  object
dtypes: object(4)
memory usage: 858.9+ KB


# Exercises XP

## What You Will Learn:

* Core NumPy operations including array creation, manipulation, and basic array operations.
* Skills in handling one-dimensional and multi-dimensional arrays.


## What You Will Create:

* A series of NumPy arrays demonstrating different operations, ranging from simple array creation to more complex manipulations.

## 🌟 Exercise 1 : Array Creation And Manipulation

Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 🌟 Exercise 2 : Type Conversion And Array Operations

Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])

## 🌟 Exercise 3 : Working With Multi-Dimensional Arrays

Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 🌟 Exercise 4 : Creating Multi-Dimensional Array With Random Numbers

Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

## 🌟 Exercise 5 : Indexing Arrays

Instructions

Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

## 🌟 Exercise 6 : Reversing Elements

Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 🌟 Exercise 7 : Identity Matrix

Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 🌟 Exercise 8 : Simple Aggregate Funcs

Instructions

Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5

## 🌟 Exercise 9 : Create Array And Change Its Structure

Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## 🌟 Exercise 10 : Conditional Selection Of Values

Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])


